/* BEC (Armenian) service worker. Generated by build.py: do not edit by hand. */
var CACHE_PREFIX = "hybec-";
var CACHE_NAME = CACHE_PREFIX + "58a36a4e238e3200";
var PRECACHE_URLS = [
  "./",
  "./index.html",
  "./css/styles.css",
  "./data/pages.js",
  "./fonts/atkinson-bold.woff2",
  "./fonts/atkinson-regular.woff2",
  "./fonts/noto-armenian-bold.woff2",
  "./fonts/noto-armenian-regular.woff2",
  "./icons/apple-touch-icon-180.png",
  "./icons/favicon.svg",
  "./icons/icon-192.png",
  "./icons/icon-512.png",
  "./icons/icon-maskable-512.png",
  "./js/app.js",
  "./manifest.webmanifest"
];

self.addEventListener("install", function (event) {
  event.waitUntil(
    caches.open(CACHE_NAME).then(function (cache) {
      return Promise.all(PRECACHE_URLS.map(function (url) {
        return cache.add(new Request(url, { cache: "reload" })).catch(function (err) {
          console.error("Service worker install failed to cache:", url, err);
          throw err;
        });
      }));
    })
  );
});

self.addEventListener("activate", function (event) {
  event.waitUntil(
    caches.keys().then(function (keys) {
      /* Only remove OLD caches of this app. Never touch caches of other apps on the same address. */
      return Promise.all(keys.filter(function (k) { return k.indexOf(CACHE_PREFIX) === 0 && k !== CACHE_NAME; }).map(function (k) { return caches.delete(k); }));
    }).then(function () { return self.clients.claim(); })
  );
});

self.addEventListener("message", function (event) {
  if (event.data && event.data.type === "SKIP_WAITING") self.skipWaiting();
});

self.addEventListener("fetch", function (event) {
  var req = event.request;
  if (req.method !== "GET") return;
  if (new URL(req.url).origin !== self.location.origin) return;
  event.respondWith(caches.match(req, { ignoreSearch: true }).then(function (hit) { return hit || fetch(req); }));
});
